// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

public final class EcaptureqProto {
  private EcaptureqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_LogEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ecaptureq.proto\022\005event\"\267\001\n\005Event\022\021\n\tti" +
      "mestamp\030\001 \001(\003\022\014\n\004uuid\030\002 \001(\t\022\016\n\006src_ip\030\003 " +
      "\001(\t\022\020\n\010src_port\030\004 \001(\r\022\016\n\006dst_ip\030\005 \001(\t\022\020\n" +
      "\010dst_port\030\006 \001(\r\022\013\n\003pid\030\007 \001(\003\022\r\n\005pname\030\010 " +
      "\001(\t\022\014\n\004type\030\t \001(\r\022\016\n\006length\030\n \001(\r\022\017\n\007pay" +
      "load\030\013 \001(\014\">\n\tHeartbeat\022\021\n\ttimestamp\030\001 \001" +
      "(\003\022\r\n\005count\030\002 \001(\003\022\017\n\007message\030\003 \001(\t\"\240\001\n\010L" +
      "ogEntry\022 \n\010log_type\030\001 \001(\0162\016.event.LogTyp" +
      "e\022%\n\revent_payload\030\002 \001(\0132\014.event.EventH\000" +
      "\022-\n\021heartbeat_payload\030\003 \001(\0132\020.event.Hear" +
      "tbeatH\000\022\021\n\007run_log\030\004 \001(\tH\000B\t\n\007payload*O\n" +
      "\007LogType\022\026\n\022LOG_TYPE_HEARTBEAT\020\000\022\030\n\024LOG_" +
      "TYPE_PROCESS_LOG\020\001\022\022\n\016LOG_TYPE_EVENT\020\002B1" +
      "\n\027com.ecapture.burp.protoB\016EcaptureqProt" +
      "oP\001Z\004./pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_Event_descriptor,
        new java.lang.String[] { "Timestamp", "Uuid", "SrcIp", "SrcPort", "DstIp", "DstPort", "Pid", "Pname", "Type", "Length", "Payload", });
    internal_static_event_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_Heartbeat_descriptor,
        new java.lang.String[] { "Timestamp", "Count", "Message", });
    internal_static_event_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_event_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_LogEntry_descriptor,
        new java.lang.String[] { "LogType", "EventPayload", "HeartbeatPayload", "RunLog", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
