// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

/**
 * <pre>
 * Base 消息定义
 * </pre>
 *
 * Protobuf type {@code event.Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:event.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    uuid_ = "";
    srcIp_ = "";
    dstIp_ = "";
    pname_ = "";
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Event();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecapture.burp.proto.Event.class, com.ecapture.burp.proto.Event.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int UUID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uuid_ = "";
  /**
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRC_IP_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object srcIp_ = "";
  /**
   * <code>string src_ip = 3;</code>
   * @return The srcIp.
   */
  @java.lang.Override
  public java.lang.String getSrcIp() {
    java.lang.Object ref = srcIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcIp_ = s;
      return s;
    }
  }
  /**
   * <code>string src_ip = 3;</code>
   * @return The bytes for srcIp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSrcIpBytes() {
    java.lang.Object ref = srcIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRC_PORT_FIELD_NUMBER = 4;
  private int srcPort_ = 0;
  /**
   * <code>uint32 src_port = 4;</code>
   * @return The srcPort.
   */
  @java.lang.Override
  public int getSrcPort() {
    return srcPort_;
  }

  public static final int DST_IP_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dstIp_ = "";
  /**
   * <code>string dst_ip = 5;</code>
   * @return The dstIp.
   */
  @java.lang.Override
  public java.lang.String getDstIp() {
    java.lang.Object ref = dstIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dstIp_ = s;
      return s;
    }
  }
  /**
   * <code>string dst_ip = 5;</code>
   * @return The bytes for dstIp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDstIpBytes() {
    java.lang.Object ref = dstIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dstIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DST_PORT_FIELD_NUMBER = 6;
  private int dstPort_ = 0;
  /**
   * <code>uint32 dst_port = 6;</code>
   * @return The dstPort.
   */
  @java.lang.Override
  public int getDstPort() {
    return dstPort_;
  }

  public static final int PID_FIELD_NUMBER = 7;
  private long pid_ = 0L;
  /**
   * <code>int64 pid = 7;</code>
   * @return The pid.
   */
  @java.lang.Override
  public long getPid() {
    return pid_;
  }

  public static final int PNAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pname_ = "";
  /**
   * <code>string pname = 8;</code>
   * @return The pname.
   */
  @java.lang.Override
  public java.lang.String getPname() {
    java.lang.Object ref = pname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pname_ = s;
      return s;
    }
  }
  /**
   * <code>string pname = 8;</code>
   * @return The bytes for pname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPnameBytes() {
    java.lang.Object ref = pname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 9;
  private int type_ = 0;
  /**
   * <code>uint32 type = 9;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int LENGTH_FIELD_NUMBER = 10;
  private int length_ = 0;
  /**
   * <code>uint32 length = 10;</code>
   * @return The length.
   */
  @java.lang.Override
  public int getLength() {
    return length_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 11;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes payload = 11;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uuid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcIp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, srcIp_);
    }
    if (srcPort_ != 0) {
      output.writeUInt32(4, srcPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dstIp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dstIp_);
    }
    if (dstPort_ != 0) {
      output.writeUInt32(6, dstPort_);
    }
    if (pid_ != 0L) {
      output.writeInt64(7, pid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pname_);
    }
    if (type_ != 0) {
      output.writeUInt32(9, type_);
    }
    if (length_ != 0) {
      output.writeUInt32(10, length_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(11, payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uuid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcIp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, srcIp_);
    }
    if (srcPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, srcPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dstIp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dstIp_);
    }
    if (dstPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, dstPort_);
    }
    if (pid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, pid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pname_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, type_);
    }
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, length_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecapture.burp.proto.Event)) {
      return super.equals(obj);
    }
    com.ecapture.burp.proto.Event other = (com.ecapture.burp.proto.Event) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (!getSrcIp()
        .equals(other.getSrcIp())) return false;
    if (getSrcPort()
        != other.getSrcPort()) return false;
    if (!getDstIp()
        .equals(other.getDstIp())) return false;
    if (getDstPort()
        != other.getDstPort()) return false;
    if (getPid()
        != other.getPid()) return false;
    if (!getPname()
        .equals(other.getPname())) return false;
    if (getType()
        != other.getType()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + SRC_IP_FIELD_NUMBER;
    hash = (53 * hash) + getSrcIp().hashCode();
    hash = (37 * hash) + SRC_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getSrcPort();
    hash = (37 * hash) + DST_IP_FIELD_NUMBER;
    hash = (53 * hash) + getDstIp().hashCode();
    hash = (37 * hash) + DST_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getDstPort();
    hash = (37 * hash) + PID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPid());
    hash = (37 * hash) + PNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPname().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecapture.burp.proto.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecapture.burp.proto.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecapture.burp.proto.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ecapture.burp.proto.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ecapture.burp.proto.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecapture.burp.proto.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecapture.burp.proto.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Base 消息定义
   * </pre>
   *
   * Protobuf type {@code event.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:event.Event)
      com.ecapture.burp.proto.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecapture.burp.proto.Event.class, com.ecapture.burp.proto.Event.Builder.class);
    }

    // Construct using com.ecapture.burp.proto.Event.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestamp_ = 0L;
      uuid_ = "";
      srcIp_ = "";
      srcPort_ = 0;
      dstIp_ = "";
      dstPort_ = 0;
      pid_ = 0L;
      pname_ = "";
      type_ = 0;
      length_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_Event_descriptor;
    }

    @java.lang.Override
    public com.ecapture.burp.proto.Event getDefaultInstanceForType() {
      return com.ecapture.burp.proto.Event.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecapture.burp.proto.Event build() {
      com.ecapture.burp.proto.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecapture.burp.proto.Event buildPartial() {
      com.ecapture.burp.proto.Event result = new com.ecapture.burp.proto.Event(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ecapture.burp.proto.Event result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.uuid_ = uuid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.srcIp_ = srcIp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.srcPort_ = srcPort_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dstIp_ = dstIp_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.dstPort_ = dstPort_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.pid_ = pid_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.pname_ = pname_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.length_ = length_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.payload_ = payload_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecapture.burp.proto.Event) {
        return mergeFrom((com.ecapture.burp.proto.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecapture.burp.proto.Event other) {
      if (other == com.ecapture.burp.proto.Event.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSrcIp().isEmpty()) {
        srcIp_ = other.srcIp_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getSrcPort() != 0) {
        setSrcPort(other.getSrcPort());
      }
      if (!other.getDstIp().isEmpty()) {
        dstIp_ = other.dstIp_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getDstPort() != 0) {
        setDstPort(other.getDstPort());
      }
      if (other.getPid() != 0L) {
        setPid(other.getPid());
      }
      if (!other.getPname().isEmpty()) {
        pname_ = other.pname_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getLength() != 0) {
        setLength(other.getLength());
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              uuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              srcIp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              srcPort_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              dstIp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              dstPort_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              pid_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              pname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              type_ = input.readUInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              length_ = input.readUInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      uuid_ = getDefaultInstance().getUuid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object srcIp_ = "";
    /**
     * <code>string src_ip = 3;</code>
     * @return The srcIp.
     */
    public java.lang.String getSrcIp() {
      java.lang.Object ref = srcIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string src_ip = 3;</code>
     * @return The bytes for srcIp.
     */
    public com.google.protobuf.ByteString
        getSrcIpBytes() {
      java.lang.Object ref = srcIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string src_ip = 3;</code>
     * @param value The srcIp to set.
     * @return This builder for chaining.
     */
    public Builder setSrcIp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      srcIp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string src_ip = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcIp() {
      srcIp_ = getDefaultInstance().getSrcIp();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string src_ip = 3;</code>
     * @param value The bytes for srcIp to set.
     * @return This builder for chaining.
     */
    public Builder setSrcIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      srcIp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int srcPort_ ;
    /**
     * <code>uint32 src_port = 4;</code>
     * @return The srcPort.
     */
    @java.lang.Override
    public int getSrcPort() {
      return srcPort_;
    }
    /**
     * <code>uint32 src_port = 4;</code>
     * @param value The srcPort to set.
     * @return This builder for chaining.
     */
    public Builder setSrcPort(int value) {

      srcPort_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 src_port = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcPort() {
      bitField0_ = (bitField0_ & ~0x00000008);
      srcPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dstIp_ = "";
    /**
     * <code>string dst_ip = 5;</code>
     * @return The dstIp.
     */
    public java.lang.String getDstIp() {
      java.lang.Object ref = dstIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dst_ip = 5;</code>
     * @return The bytes for dstIp.
     */
    public com.google.protobuf.ByteString
        getDstIpBytes() {
      java.lang.Object ref = dstIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dst_ip = 5;</code>
     * @param value The dstIp to set.
     * @return This builder for chaining.
     */
    public Builder setDstIp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dstIp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string dst_ip = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstIp() {
      dstIp_ = getDefaultInstance().getDstIp();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string dst_ip = 5;</code>
     * @param value The bytes for dstIp to set.
     * @return This builder for chaining.
     */
    public Builder setDstIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dstIp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int dstPort_ ;
    /**
     * <code>uint32 dst_port = 6;</code>
     * @return The dstPort.
     */
    @java.lang.Override
    public int getDstPort() {
      return dstPort_;
    }
    /**
     * <code>uint32 dst_port = 6;</code>
     * @param value The dstPort to set.
     * @return This builder for chaining.
     */
    public Builder setDstPort(int value) {

      dstPort_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 dst_port = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstPort() {
      bitField0_ = (bitField0_ & ~0x00000020);
      dstPort_ = 0;
      onChanged();
      return this;
    }

    private long pid_ ;
    /**
     * <code>int64 pid = 7;</code>
     * @return The pid.
     */
    @java.lang.Override
    public long getPid() {
      return pid_;
    }
    /**
     * <code>int64 pid = 7;</code>
     * @param value The pid to set.
     * @return This builder for chaining.
     */
    public Builder setPid(long value) {

      pid_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 pid = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPid() {
      bitField0_ = (bitField0_ & ~0x00000040);
      pid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object pname_ = "";
    /**
     * <code>string pname = 8;</code>
     * @return The pname.
     */
    public java.lang.String getPname() {
      java.lang.Object ref = pname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pname = 8;</code>
     * @return The bytes for pname.
     */
    public com.google.protobuf.ByteString
        getPnameBytes() {
      java.lang.Object ref = pname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pname = 8;</code>
     * @param value The pname to set.
     * @return This builder for chaining.
     */
    public Builder setPname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pname_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string pname = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPname() {
      pname_ = getDefaultInstance().getPname();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string pname = 8;</code>
     * @param value The bytes for pname to set.
     * @return This builder for chaining.
     */
    public Builder setPnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pname_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>uint32 type = 9;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>uint32 type = 9;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {

      type_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 type = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000100);
      type_ = 0;
      onChanged();
      return this;
    }

    private int length_ ;
    /**
     * <code>uint32 length = 10;</code>
     * @return The length.
     */
    @java.lang.Override
    public int getLength() {
      return length_;
    }
    /**
     * <code>uint32 length = 10;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(int value) {

      length_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 length = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000200);
      length_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 11;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 11;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000400);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:event.Event)
  }

  // @@protoc_insertion_point(class_scope:event.Event)
  private static final com.ecapture.burp.proto.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecapture.burp.proto.Event();
  }

  public static com.ecapture.burp.proto.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecapture.burp.proto.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

