// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string src_ip = 3;</code>
   * @return The srcIp.
   */
  java.lang.String getSrcIp();
  /**
   * <code>string src_ip = 3;</code>
   * @return The bytes for srcIp.
   */
  com.google.protobuf.ByteString
      getSrcIpBytes();

  /**
   * <code>uint32 src_port = 4;</code>
   * @return The srcPort.
   */
  int getSrcPort();

  /**
   * <code>string dst_ip = 5;</code>
   * @return The dstIp.
   */
  java.lang.String getDstIp();
  /**
   * <code>string dst_ip = 5;</code>
   * @return The bytes for dstIp.
   */
  com.google.protobuf.ByteString
      getDstIpBytes();

  /**
   * <code>uint32 dst_port = 6;</code>
   * @return The dstPort.
   */
  int getDstPort();

  /**
   * <code>int64 pid = 7;</code>
   * @return The pid.
   */
  long getPid();

  /**
   * <code>string pname = 8;</code>
   * @return The pname.
   */
  java.lang.String getPname();
  /**
   * <code>string pname = 8;</code>
   * @return The bytes for pname.
   */
  com.google.protobuf.ByteString
      getPnameBytes();

  /**
   * <code>uint32 type = 9;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>uint32 length = 10;</code>
   * @return The length.
   */
  int getLength();

  /**
   * <code>bytes payload = 11;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
