// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.Heartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
