// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.LogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.event.LogType log_type = 1;</code>
   * @return The enum numeric value on the wire for logType.
   */
  int getLogTypeValue();
  /**
   * <code>.event.LogType log_type = 1;</code>
   * @return The logType.
   */
  com.ecapture.burp.proto.LogType getLogType();

  /**
   * <code>.event.Event event_payload = 2;</code>
   * @return Whether the eventPayload field is set.
   */
  boolean hasEventPayload();
  /**
   * <code>.event.Event event_payload = 2;</code>
   * @return The eventPayload.
   */
  com.ecapture.burp.proto.Event getEventPayload();
  /**
   * <code>.event.Event event_payload = 2;</code>
   */
  com.ecapture.burp.proto.EventOrBuilder getEventPayloadOrBuilder();

  /**
   * <code>.event.Heartbeat heartbeat_payload = 3;</code>
   * @return Whether the heartbeatPayload field is set.
   */
  boolean hasHeartbeatPayload();
  /**
   * <code>.event.Heartbeat heartbeat_payload = 3;</code>
   * @return The heartbeatPayload.
   */
  com.ecapture.burp.proto.Heartbeat getHeartbeatPayload();
  /**
   * <code>.event.Heartbeat heartbeat_payload = 3;</code>
   */
  com.ecapture.burp.proto.HeartbeatOrBuilder getHeartbeatPayloadOrBuilder();

  /**
   * <code>string run_log = 4;</code>
   * @return Whether the runLog field is set.
   */
  boolean hasRunLog();
  /**
   * <code>string run_log = 4;</code>
   * @return The runLog.
   */
  java.lang.String getRunLog();
  /**
   * <code>string run_log = 4;</code>
   * @return The bytes for runLog.
   */
  com.google.protobuf.ByteString
      getRunLogBytes();

  com.ecapture.burp.proto.LogEntry.PayloadCase getPayloadCase();
}
