// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

/**
 * Protobuf type {@code event.LogEntry}
 */
public final class LogEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:event.LogEntry)
    LogEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogEntry.newBuilder() to construct.
  private LogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogEntry() {
    logType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LogEntry();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_LogEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_LogEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecapture.burp.proto.LogEntry.class, com.ecapture.burp.proto.LogEntry.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EVENT_PAYLOAD(2),
    HEARTBEAT_PAYLOAD(3),
    RUN_LOG(4),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return EVENT_PAYLOAD;
        case 3: return HEARTBEAT_PAYLOAD;
        case 4: return RUN_LOG;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int LOG_TYPE_FIELD_NUMBER = 1;
  private int logType_ = 0;
  /**
   * <code>.event.LogType log_type = 1;</code>
   * @return The enum numeric value on the wire for logType.
   */
  @java.lang.Override public int getLogTypeValue() {
    return logType_;
  }
  /**
   * <code>.event.LogType log_type = 1;</code>
   * @return The logType.
   */
  @java.lang.Override public com.ecapture.burp.proto.LogType getLogType() {
    com.ecapture.burp.proto.LogType result = com.ecapture.burp.proto.LogType.forNumber(logType_);
    return result == null ? com.ecapture.burp.proto.LogType.UNRECOGNIZED : result;
  }

  public static final int EVENT_PAYLOAD_FIELD_NUMBER = 2;
  /**
   * <code>.event.Event event_payload = 2;</code>
   * @return Whether the eventPayload field is set.
   */
  @java.lang.Override
  public boolean hasEventPayload() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.event.Event event_payload = 2;</code>
   * @return The eventPayload.
   */
  @java.lang.Override
  public com.ecapture.burp.proto.Event getEventPayload() {
    if (payloadCase_ == 2) {
       return (com.ecapture.burp.proto.Event) payload_;
    }
    return com.ecapture.burp.proto.Event.getDefaultInstance();
  }
  /**
   * <code>.event.Event event_payload = 2;</code>
   */
  @java.lang.Override
  public com.ecapture.burp.proto.EventOrBuilder getEventPayloadOrBuilder() {
    if (payloadCase_ == 2) {
       return (com.ecapture.burp.proto.Event) payload_;
    }
    return com.ecapture.burp.proto.Event.getDefaultInstance();
  }

  public static final int HEARTBEAT_PAYLOAD_FIELD_NUMBER = 3;
  /**
   * <code>.event.Heartbeat heartbeat_payload = 3;</code>
   * @return Whether the heartbeatPayload field is set.
   */
  @java.lang.Override
  public boolean hasHeartbeatPayload() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.event.Heartbeat heartbeat_payload = 3;</code>
   * @return The heartbeatPayload.
   */
  @java.lang.Override
  public com.ecapture.burp.proto.Heartbeat getHeartbeatPayload() {
    if (payloadCase_ == 3) {
       return (com.ecapture.burp.proto.Heartbeat) payload_;
    }
    return com.ecapture.burp.proto.Heartbeat.getDefaultInstance();
  }
  /**
   * <code>.event.Heartbeat heartbeat_payload = 3;</code>
   */
  @java.lang.Override
  public com.ecapture.burp.proto.HeartbeatOrBuilder getHeartbeatPayloadOrBuilder() {
    if (payloadCase_ == 3) {
       return (com.ecapture.burp.proto.Heartbeat) payload_;
    }
    return com.ecapture.burp.proto.Heartbeat.getDefaultInstance();
  }

  public static final int RUN_LOG_FIELD_NUMBER = 4;
  /**
   * <code>string run_log = 4;</code>
   * @return Whether the runLog field is set.
   */
  public boolean hasRunLog() {
    return payloadCase_ == 4;
  }
  /**
   * <code>string run_log = 4;</code>
   * @return The runLog.
   */
  public java.lang.String getRunLog() {
    java.lang.Object ref = "";
    if (payloadCase_ == 4) {
      ref = payload_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (payloadCase_ == 4) {
        payload_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string run_log = 4;</code>
   * @return The bytes for runLog.
   */
  public com.google.protobuf.ByteString
      getRunLogBytes() {
    java.lang.Object ref = "";
    if (payloadCase_ == 4) {
      ref = payload_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (payloadCase_ == 4) {
        payload_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (logType_ != com.ecapture.burp.proto.LogType.LOG_TYPE_HEARTBEAT.getNumber()) {
      output.writeEnum(1, logType_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (com.ecapture.burp.proto.Event) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (com.ecapture.burp.proto.Heartbeat) payload_);
    }
    if (payloadCase_ == 4) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (logType_ != com.ecapture.burp.proto.LogType.LOG_TYPE_HEARTBEAT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, logType_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.ecapture.burp.proto.Event) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.ecapture.burp.proto.Heartbeat) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecapture.burp.proto.LogEntry)) {
      return super.equals(obj);
    }
    com.ecapture.burp.proto.LogEntry other = (com.ecapture.burp.proto.LogEntry) obj;

    if (logType_ != other.logType_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getEventPayload()
            .equals(other.getEventPayload())) return false;
        break;
      case 3:
        if (!getHeartbeatPayload()
            .equals(other.getHeartbeatPayload())) return false;
        break;
      case 4:
        if (!getRunLog()
            .equals(other.getRunLog())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + logType_;
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + EVENT_PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getEventPayload().hashCode();
        break;
      case 3:
        hash = (37 * hash) + HEARTBEAT_PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeatPayload().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RUN_LOG_FIELD_NUMBER;
        hash = (53 * hash) + getRunLog().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecapture.burp.proto.LogEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ecapture.burp.proto.LogEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ecapture.burp.proto.LogEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecapture.burp.proto.LogEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecapture.burp.proto.LogEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code event.LogEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:event.LogEntry)
      com.ecapture.burp.proto.LogEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_LogEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_LogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecapture.burp.proto.LogEntry.class, com.ecapture.burp.proto.LogEntry.Builder.class);
    }

    // Construct using com.ecapture.burp.proto.LogEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      logType_ = 0;
      if (eventPayloadBuilder_ != null) {
        eventPayloadBuilder_.clear();
      }
      if (heartbeatPayloadBuilder_ != null) {
        heartbeatPayloadBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecapture.burp.proto.EcaptureqProto.internal_static_event_LogEntry_descriptor;
    }

    @java.lang.Override
    public com.ecapture.burp.proto.LogEntry getDefaultInstanceForType() {
      return com.ecapture.burp.proto.LogEntry.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecapture.burp.proto.LogEntry build() {
      com.ecapture.burp.proto.LogEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecapture.burp.proto.LogEntry buildPartial() {
      com.ecapture.burp.proto.LogEntry result = new com.ecapture.burp.proto.LogEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ecapture.burp.proto.LogEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.logType_ = logType_;
      }
    }

    private void buildPartialOneofs(com.ecapture.burp.proto.LogEntry result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 2 &&
          eventPayloadBuilder_ != null) {
        result.payload_ = eventPayloadBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          heartbeatPayloadBuilder_ != null) {
        result.payload_ = heartbeatPayloadBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecapture.burp.proto.LogEntry) {
        return mergeFrom((com.ecapture.burp.proto.LogEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecapture.burp.proto.LogEntry other) {
      if (other == com.ecapture.burp.proto.LogEntry.getDefaultInstance()) return this;
      if (other.logType_ != 0) {
        setLogTypeValue(other.getLogTypeValue());
      }
      switch (other.getPayloadCase()) {
        case EVENT_PAYLOAD: {
          mergeEventPayload(other.getEventPayload());
          break;
        }
        case HEARTBEAT_PAYLOAD: {
          mergeHeartbeatPayload(other.getHeartbeatPayload());
          break;
        }
        case RUN_LOG: {
          payloadCase_ = 4;
          payload_ = other.payload_;
          onChanged();
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              logType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getEventPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getHeartbeatPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              payloadCase_ = 4;
              payload_ = s;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int logType_ = 0;
    /**
     * <code>.event.LogType log_type = 1;</code>
     * @return The enum numeric value on the wire for logType.
     */
    @java.lang.Override public int getLogTypeValue() {
      return logType_;
    }
    /**
     * <code>.event.LogType log_type = 1;</code>
     * @param value The enum numeric value on the wire for logType to set.
     * @return This builder for chaining.
     */
    public Builder setLogTypeValue(int value) {
      logType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.event.LogType log_type = 1;</code>
     * @return The logType.
     */
    @java.lang.Override
    public com.ecapture.burp.proto.LogType getLogType() {
      com.ecapture.burp.proto.LogType result = com.ecapture.burp.proto.LogType.forNumber(logType_);
      return result == null ? com.ecapture.burp.proto.LogType.UNRECOGNIZED : result;
    }
    /**
     * <code>.event.LogType log_type = 1;</code>
     * @param value The logType to set.
     * @return This builder for chaining.
     */
    public Builder setLogType(com.ecapture.burp.proto.LogType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      logType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.event.LogType log_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      logType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecapture.burp.proto.Event, com.ecapture.burp.proto.Event.Builder, com.ecapture.burp.proto.EventOrBuilder> eventPayloadBuilder_;
    /**
     * <code>.event.Event event_payload = 2;</code>
     * @return Whether the eventPayload field is set.
     */
    @java.lang.Override
    public boolean hasEventPayload() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     * @return The eventPayload.
     */
    @java.lang.Override
    public com.ecapture.burp.proto.Event getEventPayload() {
      if (eventPayloadBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (com.ecapture.burp.proto.Event) payload_;
        }
        return com.ecapture.burp.proto.Event.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return eventPayloadBuilder_.getMessage();
        }
        return com.ecapture.burp.proto.Event.getDefaultInstance();
      }
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    public Builder setEventPayload(com.ecapture.burp.proto.Event value) {
      if (eventPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        eventPayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    public Builder setEventPayload(
        com.ecapture.burp.proto.Event.Builder builderForValue) {
      if (eventPayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        eventPayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    public Builder mergeEventPayload(com.ecapture.burp.proto.Event value) {
      if (eventPayloadBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != com.ecapture.burp.proto.Event.getDefaultInstance()) {
          payload_ = com.ecapture.burp.proto.Event.newBuilder((com.ecapture.burp.proto.Event) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          eventPayloadBuilder_.mergeFrom(value);
        } else {
          eventPayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    public Builder clearEventPayload() {
      if (eventPayloadBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        eventPayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    public com.ecapture.burp.proto.Event.Builder getEventPayloadBuilder() {
      return getEventPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    @java.lang.Override
    public com.ecapture.burp.proto.EventOrBuilder getEventPayloadOrBuilder() {
      if ((payloadCase_ == 2) && (eventPayloadBuilder_ != null)) {
        return eventPayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (com.ecapture.burp.proto.Event) payload_;
        }
        return com.ecapture.burp.proto.Event.getDefaultInstance();
      }
    }
    /**
     * <code>.event.Event event_payload = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecapture.burp.proto.Event, com.ecapture.burp.proto.Event.Builder, com.ecapture.burp.proto.EventOrBuilder> 
        getEventPayloadFieldBuilder() {
      if (eventPayloadBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = com.ecapture.burp.proto.Event.getDefaultInstance();
        }
        eventPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecapture.burp.proto.Event, com.ecapture.burp.proto.Event.Builder, com.ecapture.burp.proto.EventOrBuilder>(
                (com.ecapture.burp.proto.Event) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return eventPayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecapture.burp.proto.Heartbeat, com.ecapture.burp.proto.Heartbeat.Builder, com.ecapture.burp.proto.HeartbeatOrBuilder> heartbeatPayloadBuilder_;
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     * @return Whether the heartbeatPayload field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeatPayload() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     * @return The heartbeatPayload.
     */
    @java.lang.Override
    public com.ecapture.burp.proto.Heartbeat getHeartbeatPayload() {
      if (heartbeatPayloadBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (com.ecapture.burp.proto.Heartbeat) payload_;
        }
        return com.ecapture.burp.proto.Heartbeat.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return heartbeatPayloadBuilder_.getMessage();
        }
        return com.ecapture.burp.proto.Heartbeat.getDefaultInstance();
      }
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    public Builder setHeartbeatPayload(com.ecapture.burp.proto.Heartbeat value) {
      if (heartbeatPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        heartbeatPayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    public Builder setHeartbeatPayload(
        com.ecapture.burp.proto.Heartbeat.Builder builderForValue) {
      if (heartbeatPayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatPayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    public Builder mergeHeartbeatPayload(com.ecapture.burp.proto.Heartbeat value) {
      if (heartbeatPayloadBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != com.ecapture.burp.proto.Heartbeat.getDefaultInstance()) {
          payload_ = com.ecapture.burp.proto.Heartbeat.newBuilder((com.ecapture.burp.proto.Heartbeat) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          heartbeatPayloadBuilder_.mergeFrom(value);
        } else {
          heartbeatPayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    public Builder clearHeartbeatPayload() {
      if (heartbeatPayloadBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        heartbeatPayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    public com.ecapture.burp.proto.Heartbeat.Builder getHeartbeatPayloadBuilder() {
      return getHeartbeatPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    @java.lang.Override
    public com.ecapture.burp.proto.HeartbeatOrBuilder getHeartbeatPayloadOrBuilder() {
      if ((payloadCase_ == 3) && (heartbeatPayloadBuilder_ != null)) {
        return heartbeatPayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (com.ecapture.burp.proto.Heartbeat) payload_;
        }
        return com.ecapture.burp.proto.Heartbeat.getDefaultInstance();
      }
    }
    /**
     * <code>.event.Heartbeat heartbeat_payload = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecapture.burp.proto.Heartbeat, com.ecapture.burp.proto.Heartbeat.Builder, com.ecapture.burp.proto.HeartbeatOrBuilder> 
        getHeartbeatPayloadFieldBuilder() {
      if (heartbeatPayloadBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = com.ecapture.burp.proto.Heartbeat.getDefaultInstance();
        }
        heartbeatPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecapture.burp.proto.Heartbeat, com.ecapture.burp.proto.Heartbeat.Builder, com.ecapture.burp.proto.HeartbeatOrBuilder>(
                (com.ecapture.burp.proto.Heartbeat) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return heartbeatPayloadBuilder_;
    }

    /**
     * <code>string run_log = 4;</code>
     * @return Whether the runLog field is set.
     */
    @java.lang.Override
    public boolean hasRunLog() {
      return payloadCase_ == 4;
    }
    /**
     * <code>string run_log = 4;</code>
     * @return The runLog.
     */
    @java.lang.Override
    public java.lang.String getRunLog() {
      java.lang.Object ref = "";
      if (payloadCase_ == 4) {
        ref = payload_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (payloadCase_ == 4) {
          payload_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string run_log = 4;</code>
     * @return The bytes for runLog.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRunLogBytes() {
      java.lang.Object ref = "";
      if (payloadCase_ == 4) {
        ref = payload_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (payloadCase_ == 4) {
          payload_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string run_log = 4;</code>
     * @param value The runLog to set.
     * @return This builder for chaining.
     */
    public Builder setRunLog(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      payloadCase_ = 4;
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string run_log = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunLog() {
      if (payloadCase_ == 4) {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string run_log = 4;</code>
     * @param value The bytes for runLog to set.
     * @return This builder for chaining.
     */
    public Builder setRunLogBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payloadCase_ = 4;
      payload_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:event.LogEntry)
  }

  // @@protoc_insertion_point(class_scope:event.LogEntry)
  private static final com.ecapture.burp.proto.LogEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecapture.burp.proto.LogEntry();
  }

  public static com.ecapture.burp.proto.LogEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogEntry>
      PARSER = new com.google.protobuf.AbstractParser<LogEntry>() {
    @java.lang.Override
    public LogEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LogEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecapture.burp.proto.LogEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

