// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecaptureq.proto

// Protobuf Java Version: 3.25.1
package com.ecapture.burp.proto;

/**
 * Protobuf enum {@code event.LogType}
 */
public enum LogType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOG_TYPE_HEARTBEAT = 0;</code>
   */
  LOG_TYPE_HEARTBEAT(0),
  /**
   * <code>LOG_TYPE_PROCESS_LOG = 1;</code>
   */
  LOG_TYPE_PROCESS_LOG(1),
  /**
   * <code>LOG_TYPE_EVENT = 2;</code>
   */
  LOG_TYPE_EVENT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LOG_TYPE_HEARTBEAT = 0;</code>
   */
  public static final int LOG_TYPE_HEARTBEAT_VALUE = 0;
  /**
   * <code>LOG_TYPE_PROCESS_LOG = 1;</code>
   */
  public static final int LOG_TYPE_PROCESS_LOG_VALUE = 1;
  /**
   * <code>LOG_TYPE_EVENT = 2;</code>
   */
  public static final int LOG_TYPE_EVENT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LogType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LogType forNumber(int value) {
    switch (value) {
      case 0: return LOG_TYPE_HEARTBEAT;
      case 1: return LOG_TYPE_PROCESS_LOG;
      case 2: return LOG_TYPE_EVENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LogType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LogType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LogType>() {
          public LogType findValueByNumber(int number) {
            return LogType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ecapture.burp.proto.EcaptureqProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final LogType[] VALUES = values();

  public static LogType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LogType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:event.LogType)
}

